### ISSUE TITLE
로버트 C. 마틴의 Clean Code를 읽고 정리를 한 글

### ISSUE THREAD

**Issue by Haccoon** [Integerous/goQuality-dev-contents#10]
로버트 C. 마틴의 Clean Code를 읽고 정리를 한 글

https://sungjk.github.io/2017/07/27/clean-code.html?fbclid=IwAR2I8k1h_kkaD-Xb3VvGq6FB5ntYn6Ab3Zd_BQ42SaRYsRW3rf7VL0QeTsU

**Comment by Integerous** [comment]
공유 감사합니다! :)
Pull Request 주시면 Contributor로 자동 등록됩니다.
좋은 하루 보내세요! 👍
