### ISSUE TITLE
Android Architecture Component를 이용하여 쉽게 MVVM 기반의 안드로이드 앱 만들어보기

### ISSUE THREAD

**Issue by hongbeomi** [Integerous/goQuality-dev-contents#117]
Google에서 제공하는 AAC jetpack을 이용하여 MVVM 패턴을 적용한 예제를 통해 안드로이드에서 MVVM 패턴은 어떤 것인지 알아보고 어떻게 적용하는지 알아봅니다.

https://medium.com/hongbeomi-dev/aac%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EC%97%AC-mvvm-pattern%EC%9D%84-%EA%B5%AC%ED%98%84%ED%95%9C-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EC%95%B1-%EB%A7%8C%EB%93%A4%EA%B8%B0-1d6d73689bd0

**Comment by Integerous** [comment]
공유 감사합니다!! 👍 👍
