### ISSUE TITLE
4.프론트엔드 - Javascript 관련 - [코드리뷰를 위한 좋은 코딩 - Javascript 편] 링크 소실

### ISSUE THREAD

**Issue by Choiyos** [Integerous/goQuality-dev-contents#123]
[프론트엔드](https://github.com/Integerous/goQuality-dev-contents/tree/master/4.%20%ED%94%84%EB%A1%A0%ED%8A%B8%EC%97%94%EB%93%9C) 게시글 리스트 중에 [[코드리뷰를 위한 좋은 코딩 - Javascript 편](https://amati.io/2019/04/18/good-coding-for-codereview-on-javascript/)] 게시글에 404에러페이지가 발생합니다. 원문이 삭제되었거나 링크가 변경된 듯 합니다.

**Comment by Integerous** [comment]
오 공유 감사합니다!! 찾아보니 주소가 바뀌었네요!
https://amati.io/good-coding-for-codereview-on-javascript/

수정해두겠습니다. 감사합니다! 👍 👍
