### ISSUE TITLE
카톡방 업로드 시간제한 관련 제안입니다

### ISSUE THREAD

**Issue by Kinetic27** [Integerous/goQuality-dev-contents#130]
![image](https://user-images.githubusercontent.com/39849944/87448753-343aef80-c637-11ea-8852-21f454db7136.png)

지금은 나가신 유저분께서 `출퇴근 개발읽기` 방이니 시간제한을 두자고 제안하셨고 (아마 알림을 안끄신 분 같습니다)
적용되어서 `2. 23시~07시 사이에는 공유 금지!` 라는 규칙이 생긴 것 같습니다

하지만 늦은 시간에 글을 쓰거나 활동하시는 분들도 계시고 출퇴근 시간에 글을 읽으려면 그 전에 글이 올라와야 새로운 글이 올라오는 걸 기다리지 않고 정말로 출퇴근 시간에 읽을 수 있을 것 같습니다

( 채팅방을 보시면 오전 10시, 오후 6시, 오후 9시~10시 등 출근 후 올리시거나 쉬는 타임에 올리시는분이 꽤 보입니다)

따라서 방이 `출퇴근 개발 읽기` 인 만큼 제한을 풀어 미리 올려진 글을 출퇴근시에 읽을 수 있게 함을 제안합니다!

**Comment by Integerous** [comment]
의견 감사합니다! 조만간 단톡방에서 투표를 실시해서 말씀주신부분 개선 방향을 찾아보겠습니다ㅎ
