### ISSUE TITLE
Queue에 추가된 링크 변경 

### ISSUE THREAD

**Issue by yjaalto** [Integerous/goQuality-dev-contents#132]
안녕하세요! 고퀄리티 개발 컨텐츠 정말 잘 보고 있습니다! 
다름이 아니라 queue에 올라온 "팀 버너스리가 HTTP 프로토콜을 만든 이유" 링크가 열리지 않아 확인해보니 
[https://thinker94.com/ko/posts/bernerslee_first_http_translate/](https://thinker94.com/ko/posts/bernerslee_first_http_translate/) 로 수정되야 할 것 같습니다

**Comment by Integerous** [comment]
앗 그렇네요! 공유 감사합니다!!ㅎㅎ 👍 👍
