### ISSUE TITLE
코디미상담 후기 - 백엔드 개발자를 꿈꾸는 초보 개발자에 대한 조언

### ISSUE THREAD

**Issue by chlalstjd430** [Integerous/goQuality-dev-contents#135]
코디미상담 후기 - 백엔드 개발자를 꿈꾸는 초보 개발자에 대한 조언
http://blog.cmstown.com/2020/05/%EC%A0%95%EB%B3%B4_002/

**Comment by Integerous** [comment]
공유 감사합니다-!! 👍 👍
