### ISSUE TITLE
카톡방 관련 질문입니다

### ISSUE THREAD

**Issue by Kinetic27** [Integerous/goQuality-dev-contents#142]
여러가지 개발 관련 컨텐츠를 1번 카톡방에서 잘 받아보며 이용하고있던 이용자입니다.

16일 오전12시 쯤에 코딩테스트 관련 개발글을 올렸고 강퇴를 당했습니다
단순 기사도 아니고 저작권법 위반도 아닌데 혹시 왜 강퇴를 당했는지 이유를 알 수 있을까요?

(`카카오 블라인드 채용 문자열 압축 코틀린 풀이`글을 올렸었습니다)

**Comment by Integerous** [comment]
안녕하세요! 바쁜 일정이 있어 답변이 늦었네요 죄송합니다!
단톡방 공지사항을 확인하지 않으셨던 것 같습니다ㅠ 

많은 분들이 참여하는 방인 만큼, 취침시간을 방해하지 않기 위해서
오후 11시부터 오전 7시까지는 공유 금지 규칙을 위반하셨고, 
위반시 경고 없이 강퇴하는게 방침이었습니다..ㅠ (공지사항에 기재되어 있습니다)

그리고 공유해주신 게시물과는 관계 없다는 점 알려드립니다..!
원하신다면 2번방에 다시 참여하셔도 무방합니다. 공지사항을 읽어주시면 감사하겠습니다-!

답변이 너무 늦어 죄송하네요.. 새해 복 많이 받으세요!!

**Comment by Kinetic27** [comment]
아... 해당 규칙이 생겼었죠 제가 착각했었네요 

새해 복 많이 받으세요
