### ISSUE TITLE
레몬오렌지 나무 이태리 토분set - 내용이 개발과 관련이 있나요?

### ISSUE THREAD

**Issue by WooSung-Jung** [Integerous/goQuality-dev-contents#144]
(링크만 추가하셔도 되고, 설명을 덧붙이셔도 됩니다!)
(Label을 활용해주시면 더욱 좋습니다!)

레몬오렌지 나무 이태리 토분set는 개발이랑 전혀 상관 없는 식물에 대한 이야기인데 해당 큐에 있는 이유가 있을지 궁금합니다.

> https://github.com/Integerous/goQuality-dev-contents#mailbox-queue

> https://ohou.se/productions/247045/selling?af_siteid=net.bucketplace&shortlink=60789f07&af_referrer_uid=1602515681735-7791483989606303607&af_ad=247045&pid=af_app_invites&af_referrer_customer_id=10707809&af_ad_type=viral&af_keywords=productions

만약 없다면 삭제하고 PR 등록하겠습니다.

**Comment by Integerous** [comment]
PR 머지했습니다!! 감사합니다!!
