### ISSUE TITLE
[개발 일반] "프로그래밍할 때 알아야 할 5가지 인지 편향" 링크가 닫힌 것 같습니다

### ISSUE THREAD

**Issue by Minsoo-web** [Integerous/goQuality-dev-contents#147]
[1. 개발 일반 / 개발 문화/철학/방법론](https://github.com/Integerous/goQuality-dev-contents/tree/master/1.%20%EA%B0%9C%EB%B0%9C%20%EC%9D%BC%EB%B0%98#%EA%B0%9C%EB%B0%9C-%EB%AC%B8%ED%99%94%EC%B2%A0%ED%95%99%EB%B0%A9%EB%B2%95%EB%A1%A0)

4번째 링크인 
[프로그래밍할 때 알아야 할 5가지 인지 편향](http://www.mimul.com/pebble/default/2018/01/05/1515145860439.html) 링크가 닫혔습니다.

**Comment by WooSung-Jung** [comment]
링크가 닫힌 것을 확인하였습니다. 구글을 통하여 다른 블로그에 동일한 내용을 찾았는데 해당 블로그 글로 변경해도 괜찮을까요?
의견을 말씀해주시면 감사하겠습니다.

> https://ngio.co.kr/6090

**Comment by Minsoo-web** [comment]
@WooSung-Jung 
원본 링크의 글을 확인할 수 없어 남긴 이슈라, 대체가 가능할 동일한 내용이라면 상관 없을 것 같습니다.

**Comment by WooSung-Jung** [comment]
찾아낸 블로그 글로 대체하여 Pull requests 등록하도록 하겠습니다.

**Comment by WooSung-Jung** [comment]
> https://github.com/Integerous/goQuality-dev-contents/pull/148

해당 이슈를 수정하여 Pull requests를 등록하였습니다.

**Comment by Integerous** [comment]
PR merged
