### ISSUE TITLE
Hello Kaggle 문서 추가를 요청해도 될까요? 

### ISSUE THREAD

**Issue by stevekwon211** [Integerous/goQuality-dev-contents#150]
https://github.com/stevekwon211/Hello-Kaggle-KOR
제가 작성한 Repository이며 Kaggle이 처음인 분들을 위해  작성되었습니다!

**Comment by Integerous** [comment]
공유 감사합니다! 👍  단톡방에 우선 공유했습니다ㅎ 이후에 이 저장소에 추가될 예정입니다-!
