### ISSUE TITLE
[프론트엔드] "jQuery보다 먼저 알았으면 좋았을 것들" 링크 수정 요청

### ISSUE THREAD

**Issue by hyp3rflow** [Integerous/goQuality-dev-contents#151]
안녕하세요. 
프론트엔드 분류에 있는 "jQuery보다 먼저 알았으면 좋았을 것들" 문서의 링크가 닫힌 것 같아 이슈를 등록합니다.
같은 글을 담고 있는 열린 링크를 첨부하였으니 변경해주시면 감사하겠습니다.

[기존 링크](http://blog.jeonghwan.net/2018/01/25/before-jquery.html)
[대체 링크](https://jeonghwan-kim.github.io/2018/01/25/before-jquery.html)

**Comment by WooSung-Jung** [comment]
@hyp3rflow
해당 이슈를 확인하였습니다.
최근 유사한 사례가 있어 알려주신 링크로 대체하여 Pull request를 요청하겠습니다.
감사합니다.

> https://github.com/Integerous/goQuality-dev-contents/issues/147

**Comment by WooSung-Jung** [comment]
@hyp3rflow
해당 이슈에 대해서 Pull request를 요청하였습니다.
수정된 내역은 아래 링크에서 확인할 수 있습니다.
감사합니다.

> https://github.com/Integerous/goQuality-dev-contents/pull/152
