### ISSUE TITLE
2020회고록

### ISSUE THREAD

**Issue by chlalstjd430** [Integerous/goQuality-dev-contents#153]
(링크만 추가하셔도 되고, 설명을 덧붙이셔도 됩니다!)
(Label을 활용해주시면 더욱 좋습니다!)

2020 회고록 - 3학년 학부생에서 네이버 인턴 경험까지http://blog.cmstown.com/2021/01/2020_%ED%9A%8C%EA%B3%A0%EB%A1%9D/

**Comment by WooSung-Jung** [comment]
@Integerous @chlalstjd430 
해당 이슈를 추가해도 될까요?
