### ISSUE TITLE
방문자 패턴 - Visitor pattern

### ISSUE THREAD

**Issue by thecodinglog** [Integerous/goQuality-dev-contents#156]
(링크만 추가하셔도 되고, 설명을 덧붙이셔도 됩니다!)
(Label을 활용해주시면 더욱 좋습니다!)

주어진 도메인 문제를 해결해가면서 나타나는 새로운 문제점을 이야기해보고, 이것을 해결해 나가면서 방문자 패턴을 적용해나가는 과정을 설명합니다.

https://thecodinglog.github.io/design/2019/10/29/visitor-pattern.html

**Comment by Integerous** [comment]
공유 감사합니다!! 👍 👍
