### ISSUE TITLE
이슈 등록합니다.

### ISSUE THREAD

**Issue by eunbeeLee** [Integerous/goQuality-dev-contents#178]
(링크만 추가하셔도 되고, 설명을 덧붙이셔도 됩니다!)
(Label을 활용해주시면 더욱 좋습니다!)

취업을 위한 포트폴리오는 어떻게 준비해야하나요?

https://velog.io/@couchcoding/%EC%B7%A8%EC%97%85%EC%9D%84-%EC%9C%84%ED%95%9C-%ED%8F%AC%ED%8A%B8%ED%8F%B4%EB%A6%AC%EC%98%A4%EB%A5%BC-%EC%96%B4%EB%96%BB%EA%B2%8C-%EC%A4%80%EB%B9%84%ED%95%B4%EC%95%BC%ED%95%98%EB%82%98%EC%9A%94

**Comment by Integerous** [comment]
공유 감사합니다!! 👍 👍
