### ISSUE TITLE
글 공유 이슈입니다 :)

### ISSUE THREAD

**Issue by DolXeGoD** [Integerous/goQuality-dev-contents#181]
### 🔗 공유할 링크

https://techblog.woowahan.com/4886/

### 📣 링크에 대한 설명

설명: 우아~한 장애대응

글 내용: 우아한형제들은 장애 상황에서 고객의 신뢰를 지키기 위해서 어떻게 활동하는가

플랫폼: 우아한형제들 기술블로그

---
예상 카테고리: 백엔드 - 서버 & 클라우드 & 아키텍쳐 || 개발 일반 - 개발 문화/철학/방법론

항상 좋은 컨텐츠들 잘 보고 있습니다. 감사합니다 :)

**Comment by Integerous** [comment]
공유 감사합니다!! 👍 👍
