### ISSUE TITLE
글 공유 이슈입니다 :) - 2

### ISSUE THREAD

**Issue by DolXeGoD** [Integerous/goQuality-dev-contents#182]
### 🔗 공유할 링크

https://blog.naver.com/saltynut/220731839895

### 📣 링크에 대한 설명

설명: 좋은 API를 만들기 위한 전략

글 내용: API 서버 운영에 대한 시니어 서버 엔지니어 분의 간단한 고찰 글

플랫폼: 네이버 블로그

---
예상 카테고리: 백엔드 - 서버 & 클라우드 & 아키텍쳐 || 개발 일반 - 개발 문화/철학/방법론

항상 좋은 컨텐츠들 잘 보고 있습니다. 감사합니다 :)

**Comment by Integerous** [comment]
공유 감사합니다 :)
