### ISSUE TITLE
글 공유 이슈입니다 :)

### ISSUE THREAD

**Issue by DolXeGoD** [Integerous/goQuality-dev-contents#183]
### 🔗 공유할 링크

http://blog.hwahae.co.kr/all/tech/tech-tech/6662/

### 📣 링크에 대한 설명

설명: Python3.6 부터는 Dict가 순서를 기억한다.

글 내용: Python 3.6부터 변경된 dictionary의 해쉬 테이블 구조에 대해 분석하는 글

플랫폼: 화해 기술블로그

예상 카테고리: 언어&프레임워크 - Python

항상 좋은 컨텐츠들 잘 보고 있습니다. 감사합니다 :)

**Comment by Integerous** [comment]
확인이 늦었네요ㅠ 공유 감사합니다 :)
