### ISSUE TITLE
알고리즘 & 자료구조 목록에 있는 링크 수정

### ISSUE THREAD

**Issue by yarncha** [Integerous/goQuality-dev-contents#185]
### ✋ 질문/건의사항

안녕하세요! 좋은 자료 정리해주셔서 항상 잘 보고 있습니다 😊
정리한 자료 중 [알고리즘 & 자료구조 목록](https://github.com/Integerous/goQuality-dev-contents/tree/master/5.%20%EA%B8%B0%ED%83%80#%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98--%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0) 의 **알고리즘 & 자료구조 온라인 사전 [영문]** 링크 관련해서 건의사항이 있어 issue 남깁니다!

해당 링크는 https://xlinux.nist.gov/dads/#L 로 되어 있어서 L로 시작하는 요소에 링크가 걸려 있는데, 문서 자체인 https://xlinux.nist.gov/dads/ 로 변경하는 것이 어떨까 합니다!

작은 변경이긴 하지만 수정하게 된다면 더욱 확인이 쉬울 것 같습니다! 감사합니다!

**Comment by Integerous** [comment]
이슈 감사합니다!! 
개인 일정 때문에 확인이 늦어졌네요ㅠ 감사합니다!! 👍 👍
