### ISSUE TITLE
카톡방 추가 개설 문의

### ISSUE THREAD

**Issue by developerjhp** [Integerous/goQuality-dev-contents#187]
### ✋ 질문/건의사항

카톡방 1,2,3 이 다 차 있어서 문의 드립니다..! 네번째 단톡방을  만들어주실 수 있으신가요?? 감사합니다!

**Comment by Integerous** [comment]
안녕하세요 :) 늦은 답변 죄송합니다ㅠ 3번째 방 인원을 늘렸습니다! 3번째 방도 1500명이 꽉 차면 4번째 방을 개설하겠습니다 감사합니다! 👍

**Comment by developerjhp** [comment]
인원 늘려주셔서 정말 감사합니다^ㅡ^) !!!!
