### ISSUE TITLE
자바스크립트는 왜 프로토타입을 선택했을까?의 글을 추천합니다!

### ISSUE THREAD

**Issue by ByungyeonKim** [Integerous/goQuality-dev-contents#188]
### 🔗 공유할 링크

https://medium.com/@limsungmook/%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%EB%8A%94-%EC%99%9C-%ED%94%84%EB%A1%9C%ED%86%A0%ED%83%80%EC%9E%85%EC%9D%84-%EC%84%A0%ED%83%9D%ED%96%88%EC%9D%84%EA%B9%8C-997f985adb42

### 📣 링크에 대한 설명

'자바스크립트는 왜 프로토타입을 선택했을까?'라는 제목의 글입니다.

개인적으로 '세상을 만드는 글자, 코딩'이란 책에서 철학적인 내용을 읽었던 적이 있습니다.
그 당시엔 '왜 이런 얘기가 나올까?'라는 생각이 들었었는데 1년이 지난 지금 이 글을 읽고 이해가 됐어요. 자세한 설명과 Java 언어와의 비교 등으로 아주 잘 풀어냈습니다.

그리고 'class'라는 키워드가 어디서 나온 개념인지 등 흥미로운 부분도 많았습니다.
이 글을 추천합니다~! 👍

개발 문화/철학/방법론 분류에 없길래 올려봅니다!

**Comment by Integerous** [comment]
공유 감사합니다!! 👍 👍
