### ISSUE TITLE
CircuitBreaker를 이용한 외부 API 장애 관리

### ISSUE THREAD

**Issue by hgs-study** [Integerous/goQuality-dev-contents#193]
### 🔗 공유할 링크

https://velog.io/@hgs-study/CircuitBreaker

### 📣 링크에 대한 설명

안녕하세요 정수님!

분산 서버 아키텍처가 많아지는 만큼 장애 전파 및 관리도 중요지는 시기여서 

"CircuitBreaker를 이용한 외부 API 장애 관리"라는 글을 포스팅해봤습니다!

재밌게 봐주시면 감사하겠습니다!!!👍👍👍

**Comment by Integerous** [comment]
확인이 늦었네요! 공유 감사합니다 :) 👍

**Comment by hgs-study** [comment]
확인감사합니다!!! 👍👍👍
