### ISSUE TITLE
2021년 겨울 현장실습 근태관리 시스템 프로젝트 회고

### ISSUE THREAD

**Issue by monho** [Integerous/goQuality-dev-contents#194]
### 🔗 공유할 링크

https://mydevlife.tistory.com/12

### 📣 링크에 대한 설명

2021년 겨울 현장실습 근태관리 시스템 프로젝트 회고록입니다.

**Comment by Arc-Jung** [comment]
@monho 
개발한 내용의 스크린샷과 간단한 코드 예제, 그리고 데이터 설계에 대한 자세한 내용을 추가하여 주시면 감사하겠습니다.

**Comment by monho** [comment]
수정하였습니다.

**Comment by monho** [comment]
수정하였숩니다.

2022년 4월 26일 (화) 오전 10:20, Arc ***@***.***>님이 작성:
