### ISSUE TITLE
접근 불가능한 링크입니다 "AWS를 슬랙으로 모니터링하기"

### ISSUE THREAD

**Issue by HiiWee** [Integerous/goQuality-dev-contents#197]
### 🔗 제거를 원하는 링크

http://ww1.jeonghwan.net/

### 📣 이슈 대한 설명

접근 불가능한 링크입니다 수정 부탁드립니다!

**Comment by Integerous** [comment]
제거 완료했습니다! 기여 감사합니다 :) 👍 👍
