### ISSUE TITLE
최근에 나온 프로그래밍 정석이란 책의 리뷰와 카카오 경력 후기 입니다. 

### ISSUE THREAD

**Issue by inspire12** [Integerous/goQuality-dev-contents#2]
개발자가 코드를 대할 때 취해야할 기본 자세와 태도를 깊이 이해할 수 있습니다. 
https://www.popit.kr/bookreview-principlesofprogramming/?fbclid=IwAR0JR3FKXMdOeciOMZnQFazxRopBAXyHuMYaj7gD8Vh6pEzqxRWY6y_GGqA

카카오 인터뷰 경력 후기 입니다.
https://encyphered.github.io/blog/note/2018/09/26/kakao-interview-review.html

**Comment by Integerous** [comment]
이슈와 Pull Request 감사합니다!! :)
Label 등록에 대해 여쭈셨는데, Label은 오른쪽 두번째 줄에 Labels를 클릭하여 선택하시면 됩니다!ㅎㅎ
Label은 강제사항은 아니므로, 이슈는 편하신대로 등록해주시면 됩니다! :)

감사합니다 :)

**Comment by inspire12** [comment]
넵 감사합니다 ㅎ
