### ISSUE TITLE
접근 불가능한 링크 입니다~!

### ISSUE THREAD

**Issue by taxijjang** [Integerous/goQuality-dev-contents#207]
### 🔗 제거를 원하는 링크

https://blog.kingbbode.com/posts/spring-boot-properties-environment

### 📣 이슈 대한 설명

접근이 불가능한 링크 입니다~!
[Springboot와 Properties, Yaml Environment](https://blog.kingbbode.com/posts/spring-boot-properties-environment)

**Comment by mirrors89** [comment]
링크가 바뀐거 같네요. 아래 링크로 PR 다시 보내주시면 좋을거 같아요!

https://blog.kingbbode.com/39

**Comment by taxijjang** [comment]
> 링크가 바뀐거 같네요. 아래 링크로 PR 하시면 좋을거 같아요!
> 
> https://blog.kingbbode.com/39

https://github.com/Integerous/goQuality-dev-contents/commit/7e60e288c8e420cff06f602de2f6d5ee4beebe2e
이야기 해주신대로 주소 변경하여 commit 했습니다~! 감사합니다!

**Comment by Integerous** [comment]
확인이 늦었네요! 제보 감사합니다!!
