### ISSUE TITLE
Redisson 분산락을 이용한 동시성 제어

### ISSUE THREAD

**Issue by hgs-study** [Integerous/goQuality-dev-contents#209]
### 🔗 공유할 링크

https://velog.io/@hgs-study/redisson-distributed-lock

### 📣 링크에 대한 설명

안녕하세요 정수님!

저번에 서킷브레이커 관련 글에 이어서 이번엔 Reddion 분산락을 공유하려고 합니다!

분산 서버에서 데이터 정합성을 맞추기 위해 다양한 방법들이 있지만 

그중 하나인 Redis를 이용한 동시성 제어 글을 포스팅했습니다!

재밌게 읽어주시면 감사하겠습니다!! 👍👍👍

**Comment by Integerous** [comment]
확인이 늦었네요. 공유 감사합니다!! 👍
