### ISSUE TITLE
접근 불가능한 링크입니다.

### ISSUE THREAD

**Issue by kmh916** [Integerous/goQuality-dev-contents#210]
### 🔗 제거를 원하는 링크

https://adhrinae.github.io/posts/web-caching-explained-by-buying-milk-kr

### 📣 이슈 대한 설명

접근 불가능한 링크입니다! (404)

**Comment by mirrors89** [comment]
https://www.rinae.dev/posts/web-caching-explained-by-buying-milk-kr

확인해보니 도메인이 바뀐거 같습니다!

**Comment by taxijjang** [comment]
> https://www.rinae.dev/posts/web-caching-explained-by-buying-milk-kr
> 
> 확인해보니 도메인이 바뀐거 같습니다!

이야기 해주신대로 주소 변경하여 commit 했습니다~! 감사합니다!

**Comment by Integerous** [comment]
공유와 확인 감사합니다 👍 👍
