### ISSUE TITLE
접근 불가능한 링크 제보

### ISSUE THREAD

**Issue by daaeson** [Integerous/goQuality-dev-contents#219]
### 🔗 제거를 원하는 링크

https://insightbook.co.kr/13171

### 📣 이슈 대한 설명

1. 개발 일반
개발 문화/철학/방법론
'의도적 수련 2 - 프로그래머에게 적합한 의도적 수련'에 대해 접근이 불가능해 제보합니다.

또 [해당 원문과 같은 내용의 게시글](https://blog.insightbook.co.kr/2018/12/06/%ec%9d%98%eb%8f%84%ec%a0%81-%ec%88%98%eb%a0%a8-2-%ed%94%84%eb%a1%9c%ea%b7%b8%eb%9e%98%eb%a8%b8%ec%97%90%ea%b2%8c-%ec%a0%81%ed%95%a9%ed%95%9c-%ec%9d%98%eb%8f%84%ec%a0%81-%ec%88%98%eb%a0%a8/)을 발견하여 이 또한 제보합니다.

**Comment by Integerous** [comment]
공유 감사합니다!! 👍 👍
