### ISSUE TITLE
개발 아티클을 인용한 컨텐츠를 재인용한 경우에는 인용한 사람도 출처로서 병기했으면 합니다

### ISSUE THREAD

**Issue by kimjson** [Integerous/goQuality-dev-contents#222]
### ✋ 질문/건의사항

![IMG_0621](https://github.com/Integerous/goQuality-dev-contents/assets/15705385/bfc22d8e-f0da-4b32-8f5c-3fcfd28cecdd)

![IMG_0634](https://github.com/Integerous/goQuality-dev-contents/assets/15705385/c4814e87-e548-406a-9572-3ccffab9c223)

먼저 공지를 꼼꼼히 읽지 않고 카톡방 자체에 건의한 것에 사과드립니다. 건의 내용은 첫번째 캡처와 같습니다. 

원문 개발 아티클이 따로 있지만, 해당 아티클을 공유하며 소개하고 부연하는 컨텐츠가 있습니다. 원문 아티클만 공유하는 경우에는 상관이 없겠지만, 소개하고 부연하는 구절을 발췌했음에도 그 출처를 명시하지 않는 것은 좋은 아티클을 공유한 큐레이터의 공을 인정하지 않는 행위로 볼 수 있기 때문에 출처를 명시했으면 합니다. 

또한 안타까운 점은, 제가 깃허브 이슈에 건의를 등록해야 한다는 규칙을 지키지 않은 것은 사실이나, 어떠한 설명도 없이 관리자 분에
의해 메시지가 가려졌다는 점입니다. 1500명의 많은 참여자를 관리하시느라 힘드신 것은 이해하지만, 다소 당혹스럽습니다.

**Comment by Integerous** [comment]
안녕하세요 :) 우선 제안주셔서 감사하고 당혹스러우셨다니 죄송합니다.

careerly.co.kr는 영리 업체인 만큼, 해당 플랫폼의 글이 과도하게 공유될 경우 영리 목적으로 노출을 늘리려는 의도로 오해되기 쉽습니다.
실제로 최근에 careerly.co.kr의 링크들이 과도하게 공유되니 제한해달라는 요청도 있었습니다.

때문에 해당 플랫폼의 링크가 올라올 경우,  
처음에는 해당 링크는 제거하고 원문 링크를 공유하는 방식으로 진행하였으나,  
현재는 해당 플랫폼의 링크는 무조건 가리는 방식으로 진행하고 있습니다.

특정 업체나 플랫폼의 영리 목적으로 단톡방이 악용되는 것을 방지하면서, 1500명이 참여하고 있는 단톡방 3개 관리에 드는 노력을 최소화하려다보니, 별다른 설명 없이 메시지를 가린 점 양해 부탁드립니다. 
선한 의도로 공유해주셨으나 관리자에 의해 메시지가 가려져서 기분 상하셨을 것 같아 죄송한 마음입니다.  

하지만 2018년부터 지금까지 무료로 단톡방을 운영해왔기 때문에, 관리에 드는 노력/시간이 제한적입니다.
때문에 제안해주신 '재인용 출처 명시'는 반려할 수 밖에 없음을 알려드립니다.

주신 제안을 수락하지 못하여 죄송하고, 그래도 제안주셔서 감사합니다.
