### ISSUE TITLE
Java카테고리 링크 페이지에러

### ISSUE THREAD

**Issue by BKJang** [Integerous/goQuality-dev-contents#35]
Java카테고리에서 '왜-자바에서-static의-사용을-지양해야-하는가' 링크를 클릭하면 페이지 에러가 납니다. 컨텐츠가 없어진듯합니다.

http://tech.thegajago.com/2016/02/20/%EC%99%9C-%EC%9E%90%EB%B0%94%EC%97%90%EC%84%9C-static%EC%9D%98-%EC%82%AC%EC%9A%A9%EC%9D%84-%EC%A7%80%EC%96%91%ED%95%B4%EC%95%BC-%ED%95%98%EB%8A%94%EA%B0%80/

**Comment by Integerous** [comment]
이슈 리포트 감사합니다!
아무래도 http://tech.thegajago.com/ 블로그 자체의 문제인 것 같네요.
컨텐츠 자체가 일시적으로 문제있거나 삭제된 것들만 모아놓는 카테고리를 만들겠습니다.

알려주셔서 정말 감사드려요! :) 👍 👍
