### ISSUE TITLE
머신러닝 공부 순서, 방법 및 강의 정리

### ISSUE THREAD

**Issue by JustinChoi21** [Integerous/goQuality-dev-contents#36]
머신러닝 공부 순서, 방법 및 강의 정리
http://gomcine.tistory.com/entry/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D-%EA%B3%B5%EB%B6%80-%EC%88%9C%EC%84%9C-%EB%B0%8F-%EB%B0%A9%EB%B2%95-%EA%B0%95%EC%9D%98-%EC%A0%95%EB%A6%AC

**Comment by Integerous** [comment]
유익한 컨텐츠 공유 감사합니다!! :)
머신러닝쪽 컨텐츠는 잘 공유가 안되서 고민이었는데
가뭄에 단비같은 공유네요ㅎ

앞으로도 종종 부탁드리겠습니다!
좋은 하루 보내세요 :) 👍
