### ISSUE TITLE
자바스크립트 Functor(펑터)란

### ISSUE THREAD

**Issue by moonformeli** [Integerous/goQuality-dev-contents#40]
https://midojeong.github.io/2018/04/07/functors-and-categories/

**Comment by Integerous** [comment]
공유 감사합니다 :) 👍

**Comment by ENvironmentSet** [comment]
@moonformeli @Integerous 

midojeong님이 블로그를 [다른 곳으로 욺기신 것 같습니다.](https://tpgns.github.io/)
확인해주시면 감사하겠습니다.

**Comment by moonformeli** [comment]
@ENvironmentSet @Integerous 

https://tpgns.github.io/2018/04/07/functors-and-categories/

새롭게 옮기신 블로그입니다.
내용은 동일합니다.
감사합니다.

**Comment by moonformeli** [comment]
@Integerous 

확인부탁드립니다.
