### ISSUE TITLE
데이터 분석, 먹고 들어가기 위한 SQL 공부법(1편)

### ISSUE THREAD

**Issue by myeongjin2** [Integerous/goQuality-dev-contents#5]
데이터 분석, 먹고 들어가기 위한 SQL 공부법(1편)
https://brunch.co.kr/@minu-log/5

**Comment by Integerous** [comment]
컨텐츠 공유 감사합니다 :) 👍 
Pull Request 주시면 Contributor로 자동 등록됩니다ㅎ
