### ISSUE TITLE
Lambda 한개로 만드는 On-demand Image Resizing

### ISSUE THREAD

**Issue by jinhokong** [Integerous/goQuality-dev-contents#55]
(링크만 추가하셔도 되고, 설명을 덧붙이셔도 됩니다!)
(Label을 활용해주시면 더욱 좋습니다!)
https://engineering.huiseoul.com/lambda-%ED%95%9C%EA%B0%9C%EB%A1%9C-%EB%A7%8C%EB%93%9C%EB%8A%94-on-demand-image-resizing-d48167cc1c31

**Comment by Integerous** [comment]
늦은 확인 죄송합니다.
개인 일정이 있어서 4월 13일부터 정상적으로 관리될 예정입니다.
공유 감사합니다! :)
