### ISSUE TITLE
읽을거리 2개 공유합니다!

### ISSUE THREAD

**Issue by zion830** [Integerous/goQuality-dev-contents#58]
**개발자 면접 질문을 공개합니다**
[링크](https://medium.com/lookpin-engineering/%EA%B0%9C%EB%B0%9C%EC%9E%90-%EB%A9%B4%EC%A0%91-%EC%A7%88%EB%AC%B8%EB%A6%AC%EC%8A%A4%ED%8A%B8%EB%A5%BC-%EA%B3%B5%EA%B0%9C%ED%95%A9%EB%8B%88%EB%8B%A4-ae6e55d94f27)

**왜 레진코믹스는 안드로이드 부터 개발했는가?**
[링크](https://medium.com/@xguru/%EC%99%9C-%EB%A0%88%EC%A7%84%EC%BD%94%EB%AF%B9%EC%8A%A4%EB%8A%94-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EB%B6%80%ED%84%B0-%EA%B0%9C%EB%B0%9C%ED%96%88%EB%8A%94%EA%B0%80-fed56bec12d2)

**Comment by Integerous** [comment]
늦은 확인 죄송합니다. 개인 일정으로 4월 13일부터 정상적으로 운영할 예정입니다.
공유 감사합니다! :) 👍 👍
