### ISSUE TITLE
2019 AWS Summit Seoul 참관기 

### ISSUE THREAD

**Issue by jinhokong** [Integerous/goQuality-dev-contents#63]
(링크만 추가하셔도 되고, 설명을 덧붙이셔도 됩니다!)
(Label을 활용해주시면 더욱 좋습니다!)

2019 AWS Summit Seoul 참관기 day 1 / 2

https://engineering.huiseoul.com/2019-aws-summit-seoul-%EC%B0%B8%EA%B4%80%EA%B8%B0-day-1-2-7232b47135d1

**Comment by Integerous** [comment]
공유 감사합니다!! 👍 👍
