### ISSUE TITLE
[프로그래머 필독서] 컨텐츠 링크 변경 요청 

### ISSUE THREAD

**Issue by hongminpark** [Integerous/goQuality-dev-contents#73]
내 마음대로 선정한 개발자/프로그래머 추천도서(필독서) 50선(20190409) / https://www.sangkon.com/good_books_for_dev_2018/

로 링크변경 요청드립니다 
#72

**Comment by Integerous** [comment]
제가 확인이 너무 늦었네요! 이슈 감사합니다!! 👍 👍
