### ISSUE TITLE
오픈채팅방 인원 늘려주세요~

### ISSUE THREAD

**Issue by dongwonKim** [Integerous/goQuality-dev-contents#84]
1500명 제한이라서 참여가 되질 않네요..
인원 제한을 늘려주세요~

**Comment by CheshireCoder** [comment]
친목 도모의 목적이 없다면 오픈 채팅방을 없애고,
채팅방이 필요한데 인원이 그 정도라면 디스코드 같은 곳으로 채팅방을 이전하는게 나아 보입니다.

**Comment by Integerous** [comment]
@dongwonKim 안녕하세요! 

카카오톡 오픈채팅방이 설정할 수 있는 최대인원수가 1500명이라 
더 이상 인원을 늘릴 수 없는 상황입니다. 가끔 나가시는 분들이 계시니 가끔 확인해보시다가 들어오시면 될 것 같습니다! 아니면 페이스북 {출퇴근길 개발 읽기} 페이지로 구독해주셔도 좋을 것 같습니다!

@CheshireCoder 
안녕하세요! 의견 감사합니다!
현재 카카오톡 오픈채팅방을 이전할 계획은 없습니다. 하지만
말씀주신 디스코드나 텔레그램, 혹은 슬랙에 추가적으로 채널을 개설하는 것을 고려해보겠습니다-!
