### ISSUE TITLE
프로젝트에서 jQuery 사용을 그만두기로 결심한 이유

### ISSUE THREAD

**Issue by moonformeli** [Integerous/goQuality-dev-contents#90]
(링크만 추가하셔도 되고, 설명을 덧붙이셔도 됩니다!)
(Label을 활용해주시면 더욱 좋습니다!)

프로젝트에서 jQuery 사용을 그만두기로 결심한 이유

https://medium.com/%EC%98%A4%EB%8A%98%EC%9D%98-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EC%97%90%EC%84%9C-jquery-%EC%9D%98-%EC%82%AC%EC%9A%A9%EC%9D%84-%EA%B7%B8%EB%A7%8C%EB%91%90%EA%B2%A0%EB%8B%A4%EA%B3%A0-%EA%B2%B0%EC%8B%AC%ED%95%9C-%EC%9D%B4%EC%9C%A0-45379cba95b6

좋은 하루 보내세요.

**Comment by Integerous** [comment]
공유 감사합니다!! 👍 👍
