### ISSUE TITLE
Puppeteer 를 이용해 간단한 React App 을 테스트 해봤다

### ISSUE THREAD

**Issue by moonformeli** [Integerous/goQuality-dev-contents#94]
(링크만 추가하셔도 되고, 설명을 덧붙이셔도 됩니다!)
(Label을 활용해주시면 더욱 좋습니다!)
https://medium.com/%EC%98%A4%EB%8A%98%EC%9D%98-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D/puppeteer-%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%B4-%EA%B0%84%EB%8B%A8%ED%95%9C-react-app-%EC%9D%84-%ED%85%8C%EC%8A%A4%ED%8A%B8-%ED%95%B4%EB%B4%A4%EB%8B%A4-6581441f4607

**Comment by Integerous** [comment]
공유 감사합니다! 👍  단톡방에 올려주신거면 여기에는 안올리셔도 됩니다ㅎㅎ
