### ISSUE TITLE
[B급 프로그래머] 초급 개발자가 알아야 하는 12가지 기술

### ISSUE THREAD

**Issue by eojin312** [Integerous/goQuality-dev-contents#98]
(링크만 추가하셔도 되고, 설명을 덧붙이셔도 됩니다!)
(Label을 활용해주시면 더욱 좋습니다!)
http://bit.ly/2q5kDhO

토요일, 10월 20, 2018
[B급 프로그래머] 초급 개발자가 알아야 하는 12가지 기술
트위터를 읽다가 발견한 글이 있어 간단하게 정리해보았다.

초급 개발자가 알아야 하는 12가지 기술은?(순서 무관)

관계형 데이터베이스 동작 방식(언제나 유용)
일반적인 HTTP 동작 방식
특정 언어에서 코드 디버깅 방법(다른 언어에서도 엇비슷하므로 지식을 재사용할 수 있다)
코드를 찾는 방법(IDE나 명령행에서 grep을 사용)
정규 표현식 기초(직전 항목에서 코드를 찾는 방법에도 적용 가능)
검색 엔진으로 직면한 문제의 해법을 찾는 방법
git 운영 방법(다른 형상 관리 시스템이라도 큰 문제 없음)
질문할 가치가 없다고 생각할 때에도 질문하기
시간대(TZ) 동작 방식(농담이 아님. 많은 개발자들이 혼동을 겪는 부분임)
유니코드와 UTF-8 동작 방식
캐시 동작 방식(CPU, 메모리, 디스크)
여기에 IDE 사용 방법(자유자재로...)과 셸/CMD 기초 사용법, 네트워크 관련 일반 지식이 더해지면 초급 개발자로서 한 몫을 다 하리라 생각한다.

EOB

**Comment by Integerous** [comment]
공유 감사합니다!! 👍 👍
